### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by petrleocompel** [magicmark/composerize#10]
Output is missing image what i should use
It's easy to reproduce.
Input
```
docker run -t --name="youtrack" uniplug/youtrack
```
Output
```
version: 3
services:
    youtrack: {}
```
Expected output
```
version: 3
services:
    youtrack:
        image: uniplug/youtrack
```

**Comment by magicmark** [comment]
Thanks for opening the issue! This is to do with how spawn-args treats arguments separated by `=` :(

```
> spawnargs('--a="b"', { removequotes: "always" })                                             
[ '--a=', 'b' ]                                 
> spawnargs('--a=b', { removequotes: "always" })                                               
[ '--a=b' ]     
```

This will be fixed by https://github.com/magicmark/composerize/issues/12

**Comment by magicmark** [comment]
This should be now fixed :)

Let me know if you have any more issues!

**Comment by petrleocompel** [comment]
Is website updated ? https://composerize.com/ ??

**Comment by petrleocompel** [comment]
Also I tried local installation of composerize and still it's not ok.

Command
```
composerize docker run --name "postgis" -e POSTGRES_USER=app -e POSTGRES_PASS=app -e POSTGRES_DBNAME=elza12  -p 5432:5432 -d -t kartoza/postgis
```
Generates
```
version: 3
services:
    run:
        container_name: postgis
        environment:
            - POSTGRES_USER=app
            - POSTGRES_PASS=app
            - POSTGRES_DBNAME=elza12
        ports:
            - '5432:5432'
        image: run
```

Image is wrong -> `run` is not my image is docker command `kartoza/postgis`

But when you will delete `-d -t` it works. You should ignore `-d`, `-t` `-i`
