### ISSUE TITLE
Port numbers converted to booleans instead of numbers/mapping string

### ISSUE THREAD

**Issue by danieljue** [magicmark/composerize#113]
**Do you want to request a *feature* or report a *bug*?**
bug
**Please provide a sample input docker run command**
```
docker run \     --name testneo4j \     -p7474:7474 -p7687:7687 \     -d \     -v $HOME/neo4j/data:/data \     -v $HOME/neo4j/logs:/logs \     -v $HOME/neo4j/import:/var/lib/neo4j/import \     -v $HOME/neo4j/plugins:/plugins \     --env NEO4J_AUTH=neo4j/test \     neo4j:latest
```

**What is the current output?***
```
version: '3.3'
services:
    neo4j:
        container_name: testneo4j
        ports:
            - true
            - true
        volumes:
            - '$HOME/neo4j/data:/data'
            - '$HOME/neo4j/logs:/logs'
            - '$HOME/neo4j/import:/var/lib/neo4j/import'
            - '$HOME/neo4j/plugins:/plugins'
        environment:
            - NEO4J_AUTH=neo4j/test
        image: 'neo4j:latest'
```

**What is the expected/desired output?**
```
version: '3.3'
services:
    neo4j:
        container_name: testneo4j
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
            - '$HOME/neo4j/data:/data'
            - '$HOME/neo4j/logs:/logs'
            - '$HOME/neo4j/import:/var/lib/neo4j/import'
            - '$HOME/neo4j/plugins:/plugins'
        environment:
            - NEO4J_AUTH=neo4j/test
        image: 'neo4j:latest'
```
