### ISSUE TITLE
environment parsed not correct

### ISSUE THREAD

**Issue by liudonghua123** [magicmark/composerize#120]
I want to convert a docker run command from https://docs.konghq.com/install/docker/ to docker-compose.yml and I tried https://composerize.com/, but the parsed output seems problematical.

**Do you want to request a *feature* or report a *bug*?**
bug

**Please provide a sample input docker run command**
```
docker run -d --name kong \
     --network=kong-net \
     -e "KONG_DATABASE=postgres" \
     -e "KONG_PG_HOST=kong-database" \
     -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
     -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
     -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
     -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
     -p 8000:8000 \
     -p 8443:8443 \
     -p 8001:8001 \
     -p 8444:8444 \
     kong:latest
```

**What is the current output?***
```
C:\Users\Liu.D.H>composerize docker run -d --name kong --network=kong-net -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" -e "KONG_PROXY_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" -p 8000:8000 -p 8443:8443 -p 8001:8001 -p 8444:8444 kong:latest
version: '3.3'
services:
    kong:
        container_name: kong
        network_mode: kong-net
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=kong-database
            - KONG_CASSANDRA_CONTACT_POINTS=kong-database
            - KONG_PROXY_ACCESS_LOG=/dev/stdout
            - KONG_ADMIN_ACCESS_LOG=/dev/stdout
            - KONG_PROXY_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_ERROR_LOG=/dev/stderr
            - 'KONG_ADMIN_LISTEN=0.0.0.0:8001,'
        ports:
            - '8000:8000'
            - '8443:8443'
            - '8001:8001'
            - '8444:8444'
        image: 'kong:latest'

C:\Users\Liu.D.H>
```

**What is the expected/desired output?**
```
version: '3.3'
services:
    kong:
        container_name: kong
        network_mode: kong-net
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=kong-database
            - KONG_CASSANDRA_CONTACT_POINTS=kong-database
            - KONG_PROXY_ACCESS_LOG=/dev/stdout
            - KONG_ADMIN_ACCESS_LOG=/dev/stdout
            - KONG_PROXY_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_LISTEN='0.0.0.0:8001, 0.0.0.0:8444 ssl'
        ports:
            - '8000:8000'
            - '8443:8443'
            - '8001:8001'
            - '8444:8444'
        image: 'kong:latest'
```

**Comment by joaoeudes7** [comment]
I'm going through the same problem with this script

**Comment by sharevb** [comment]
Assuming this is the right output (actually environment is a string array so quotes are on whole lines) :
```
version: '3.3'
services:
    kong:
        container_name: kong
        network_mode: kong-net
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=kong-database
            - KONG_CASSANDRA_CONTACT_POINTS=kong-database
            - KONG_PROXY_ACCESS_LOG=/dev/stdout
            - KONG_ADMIN_ACCESS_LOG=/dev/stdout
            - KONG_PROXY_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_ERROR_LOG=/dev/stderr
            - 'KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl'
        ports:
            - '8000:8000'
            - '8443:8443'
            - '8001:8001'
            - '8444:8444'
        image: 'kong:latest'
```
