### ISSUE TITLE
Does not support  parametrized containers

### ISSUE THREAD

**Issue by kassanmoor** [magicmark/composerize#19]
for example `docker run -d -P -v /var/log:/log mthenw/frontail /log/syslog`
is parsed incorrectly , also try with

`docker run --name="logspout" --volume=/var/run/docker.sock:/var/run/docker.sock \
	gliderlabs/logspout syslog+tls://logs.papertrailapp.com:55555`

**Comment by sharevb** [comment]
Now as of #568 :
```
# ignored options for 'frontail'
# -P
version: '3.3'
services:
    frontail:
        volumes:
            - '/var/log:/log'
        image: mthenw/frontail
        command: /log/syslog
```
and
```
version: '3.3'
services:
    logspout:
        container_name: logspout
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        image: gliderlabs/logspout
        command: 'syslog+tls://logs.papertrailapp.com:55555'
```
