### ISSUE TITLE
Use the "extra" Docker parameters

### ISSUE THREAD

**Issue by peter-kehl** [magicmark/composerize#219]
**Do you want to request a *feature* or report a *bug*?**
Probably a bug.

**Please provide a sample input docker run command**
```
docker run -p 9000:9000 --name minio-s3  -e "MINIO_ACCESS_KEY=my-AWS-access-key"  -e "MINIO_SECRET_KEY=my-AWS-secret-key" minio/minio gateway s3
```

**What is the current output?***
```
version: '3.3'
services:
    s3:
        ports:
            - '9000:9000'
        container_name: minio-s3
        environment:
            - MINIO_ACCESS_KEY=my-AWS-access-key
            - MINIO_SECRET_KEY=my-AWS-secret-key
        image: s3
```

**What is the expected/desired output?**
I don't know, since I'm not a Docker Compose expert. But, it should somehow use `minio/minio gateway`, too. Most likely:
```
version: '3.3'
services:
    s3:
        ports:
            - '9000:9000'
        container_name: minio-s3
        environment:
            - MINIO_ACCESS_KEY=my-AWS-access-key
            - MINIO_SECRET_KEY=my-AWS-secret-key
        image: minio/minio
        command: minio gateway s3
```

**Comment by abmruman** [comment]
For me it is showing a different output. I have also tried without the backslashes ( `\` )

input:
```
docker run -p 9000:9000 --name minio-s3  \
  -e "MINIO_ACCESS_KEY=my-AWS-access-key"  \
  -e "MINIO_SECRET_KEY=my-AWS-secret-key" \
  minio/minio gateway s3
```

output: (which is incorrect)
```
version: '3.3'
services:
    s3:
        ports:
            - '9000:9000'
        container_name: minio-s3
        environment:
            - MINIO_ACCESS_KEY=my-AWS-access-key
            - MINIO_SECRET_KEY=my-AWS-secret-key
        image: s3
```

Here, the `image` should be `minio/minio` and `command` `gateway s3`


Correct output might look like this:
```
version: '3.3'
services:
    s3:
        ports:
            - '9000:9000'
        container_name: minio-s3
        environment:
            - MINIO_ACCESS_KEY=my-AWS-access-key
            - MINIO_SECRET_KEY=my-AWS-secret-key
        image: minio/minio
        command: "gateway s3"
```

**Comment by mat813** [comment]
Fun fact, I was trying to compose-ize minio and ran into the same problem :stuck_out_tongue_winking_eye:

**Comment by sharevb** [comment]
Is this output ok for you ?
```
version: '3.3'
services:
    minio:
        ports:
            - '9000:9000'
        container_name: minio-s3
        environment:
            - MINIO_ACCESS_KEY=my-AWS-access-key
            - MINIO_SECRET_KEY=my-AWS-secret-key
        image: minio/minio
        command: gateway
        args:
            - s3
```
