### ISSUE TITLE
Network Mode is ignored

### ISSUE THREAD

**Issue by LeoDJ** [magicmark/composerize#25]
**Do you want to request a *feature* or report a *bug*?**
The but is that the `--network` parameter get's completely ignored as far as I can see.

**Please provide a sample input docker run command**
```
docker run \ -d \ --name plex  --network=host \ -e TZ="<timezone>" \ -e PLEX_CLAIM="<claimToken>" \ -v <path/to/plex/database>:/config \ -v <path/to/transcode/temp>:/transcode \ -v <path/to/media>:/data \ plexinc/pms-docker
```

**What is the current output?***
```
version: 3
services:
    pms-docker:
        container_name: plex
        environment:
            - TZ=<timezone>
            - PLEX_CLAIM=<claimToken>
        volumes:
            - '<path/to/plex/database>:/config'
            - '<path/to/transcode/temp>:/transcode'
            - '<path/to/media>:/data'
        image: plexinc/pms-docker
```

**What is the expected/desired output?**
```
version: 3
services:
    pms-docker:
        container_name: plex
        network_mode: 'host'
        environment:
            - TZ=<timezone>
            - PLEX_CLAIM=<claimToken>
        volumes:
            - '<path/to/plex/database>:/config'
            - '<path/to/transcode/temp>:/transcode'
            - '<path/to/media>:/data'
        image: plexinc/pms-docker
```
