### ISSUE TITLE
Missing Mappings for command, cap-add, pid, privileged etc

### ISSUE THREAD

**Issue by seffyroff** [magicmark/composerize#30]
Checked 👍 
**Do you want to request a *feature* or report a *bug*?**
Bug. 🐛 
**Please provide a sample input docker run command**
```
docker run -d --name storageos \
    -e HOSTNAME \
    -e ADVERTISE_IP=xxx.xxx.xxx.xxx \
    -e JOIN=xxxxxxxxxxxxxxxxx \
    --net=host \
    --pid=host \
    --privileged \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    -v /var/lib/storageos:/var/lib/storageos:rshared \
    -v /run/docker/plugins:/run/docker/plugins \
    storageos/node:0.10.0 server
```

**What is the current output?***
```
version: 3
services:
    server:
        container_name: storageos
        environment:
            - HOSTNAME
            - ADVERTISE_IP=xxx.xxx.xxx.xxx
            - JOIN=xxxxxxxxxxxxxxxxx
        devices:
            - /dev/fuse
        volumes:
            - '/var/lib/storageos:/var/lib/storageos:rshared'
            - '/run/docker/plugins:/run/docker/plugins'
        image: server
```

**What is the expected/desired output?**

```
version: '3'
services:
    node:
        container_name: storageos
        command: server
        network_mode: "host"
        pid: "host"
        privileged: true
        cap_add:
            - SYS_ADMIN
        environment:
            - HOSTNAME
            - ADVERTISE_IP=${VAR_ADVERTISE_IP}
            - JOIN=${VAR_JOIN_TOKEN}
        devices:
            - /dev/fuse
        volumes:
            - '/var/lib/storageos:/var/lib/storageos:rshared'
            - '/run/docker/plugins:/run/docker/plugins'
        image: 'storageos/node:0.10.0'
```
