### ISSUE TITLE
Parameter parsing fails if whitespace is omitted

### ISSUE THREAD

**Issue by rjoonas** [magicmark/composerize#35]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**Please provide a sample input docker run command**
```
npx composerize docker run -p1234:5678 postgres
```

**What is the current output?***
```
version: 3
services:
    postgres:
        ports:
            - true
        image: postgres
```

**What is the expected/desired output?**
```
version: '3'
services:
    postgres:
        ports:
            - '1234:5678'
        image: 'postgres'
```
