### ISSUE TITLE
ip, mac address, hostname, network parameters ignored

### ISSUE THREAD

**Issue by psychowood** [magicmark/composerize#359]
As per subject, I noticed a bunch of arguments that either are not mapped correctly (--net -> network_mode) or are completely ignored (--ip --mac-address --hostname, I'd guess --ip6 too).

**Please provide a sample input docker run command**
```
docker run -d --name test --restart=always --net=homenet --ip=192.168.1.9 --mac-address=00:00:00:00:00:09 --hostname myhost -v /import/settings:/settings -v /import/media:/media -p 8080:8080 -e UID=1000 -e GID=1000 repo/image
```

**What is the current output?***
```
version: '3.3'
services:
    image:
        container_name: test
        restart: always
        network_mode: homenet
        volumes:
            - '/import/settings:/settings'
            - '/import/media:/media'
        ports:
            - '8080:8080'
        environment:
            - UID=1000
            - GID=1000
        image: repo/image
```

EDIT: ok this is actually a little bit more complicated than the previous example. This should be correct/expected output:

**What is the expected/desired output?**
```
version: '3.3'
services:
    image:
        container_name: test
        restart: always
        hostname: myhost
        mac_address: 00:00:00:00:00:09
        networks: 
                homenet:
                        ipv4_address: 192.168.1.9
        volumes:
            - '/import/settings:/settings'
            - '/import/media:/media'
        ports:
            - '8080:8080'
        environment:
            - UID=1000
            - GID=1000
        image: repo/image

networks:
  homenet:
    external:
      name: homenet

```
