### ISSUE TITLE
Support for bind mounts

### ISSUE THREAD

**Issue by MitchellCash** [magicmark/composerize#412]
**Do you want to request a *feature* or report a *bug*?**

Feature

**Please provide a sample input docker run command**

```
docker run --mount type=bind,source=./logs,target=/usr/src/app/logs [IMAGE]
```

**What is the current output?***

Not supported (no output).

**What is the expected/desired output?**

```
volumes:
  - type: bind
    source: ./logs
    target: /usr/src/app/logs
```

**Comment by magicmark** [comment]
Thanks for the report! Wanna take a stab at a fix for this? Should be able to just add the mappings in here https://github.com/magicmark/composerize/blob/master/src/mappings.js

thanks!

**Comment by MitchellCash** [comment]
@magicmark will do! Had a spare moment and quickly threw this together https://github.com/magicmark/composerize/compare/master...MitchellCash:mount-support

Still need to do tests and some better handling in the logic. The one issue I came across in this initial version that I might need some pointers for is I have it outputting like below:

```yml
version: '3.3'
services:
    nginx:
        volumes:
            -
                type: type=bind
                source: source=./logs
                target: target=/usr/src/app/logs
        image: nginx
```

The `type` key is being put on the next line to the dash. I guess this is coming from the `yamljs` library but might be wrong, any pointers for me for when I get a moment to pick this up again?
