### ISSUE TITLE
Support for --tty, -t command

### ISSUE THREAD

**Issue by jonelleamio** [magicmark/composerize#483]
I'm trying to convert this command from jwilder/nginx-proxy
```
docker run --volumes-from nginx \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    -v $(pwd):/etc/docker-gen/templates \
    -t jwilder/docker-gen -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
```
And then I have this output

```
version: '3.3'
services:
    etc:
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
            - '$(pwd):/etc/docker-gen/templates'
        image: /etc/nginx/conf.d/default.conf
```
Thank's !
