### ISSUE TITLE
Commands after the image does not work.

### ISSUE THREAD

**Issue by ederfdias** [magicmark/composerize#484]
**Looks like a bug.**

**Example:**
```
docker run --rm -it -p 50000:50000 -p 8080:8080 --name opcplc mcr.microsoft.com/iotedge/opc-plc:latest --pn=50000 --autoaccept --nospikes --nodips --nopostrend --nonegtrend --nodatavalues --sph --sn=25 --sr=10 --st=uint --fn=5 --fr=1 --ft=uint
```

**What is the current output?***
```
version: '3.3'
services:
    iotedge:
        ports:
            - '50000:50000'
            - '8080:8080'
        container_name: opcplc
        image: 'mcr.microsoft.com/iotedge/opc-plc:latest'
```

**What is the expected/desired output?**
```
version: '3.3'
services:
    iotedge:
        ports:
            - '50000:50000'
            - '8080:8080'
        container_name: opcplc
        image: 'mcr.microsoft.com/iotedge/opc-plc:latest'
        args: 
            - '--pn=50000'
            - '--autoaccept'
            - 'and so on...'
```

**Comment by nafg** [comment]
I had a worse case of this:

Input:
```
docker run -ti --rm -v ~/.ivy2:/root/.ivy2 -v ~/.sbt:/root/.sbt -v $PWD:/app -w /app mozilla/sbt sbt shell
```

Output:
```
version: '3.3'
services:
    shell:
        volumes:
            - '~/.ivy2:/root/.ivy2'
            - '~/.sbt:/root/.sbt'
            - '$PWD:/app'
        image: shell
```

So it gets the image completely wrong, and ignores `-w`

**Comment by spannerman79** [comment]
Indeed.  This is still an issue to this day.

Input:

```
docker run --detach --name stationeers --publish 27016:27016/udp hetsh/stationeers -load "My saved game" moon
```

Output:

```yml
version: '3.3'
services:
    moon:
        container_name: stationeers
        ports:
            - '27016:27016/udp'
        image: moon
```
Completley borked.

**Comment by ansred** [comment]
Still an issue not being recognizing the args in the docker run command `--rm`

Example:

`docker run --rm -d -p 2022:22 --name workloader-ssh ansred/ubuntu-workloader-ssh`

Current output (Missing the --rm arg)

```
version: '3.3'
services:
    ubuntu-workloader-ssh:
        ports:
            - '2022:22'
        container_name: workloader-ssh
        image: ansred/ubuntu-workloader-ssh
```
