### ISSUE TITLE
ERROR: Version in "./docker-compose.yml" is invalid - it should be a string.

### ISSUE THREAD

**Issue by davidmankin** [magicmark/composerize#49]
**Do you want to request a *feature* or report a *bug*?**

Bug

**Please provide a sample input docker run command**
```
docker run --init --rm -d -e foo=bar container:latest
```

**What is the current output?***
```
version: 3
services:
    container:
        environment:
            - foo=bar
        image: 'container:latest'
```

**What is the expected/desired output?**
```
version: "3"
services:
    container:
        environment:
            - foo=bar
        image: 'container:latest'
```

The version should be a string.  docker-compose tells me:

```
ERROR: Version in "./docker-compose.yml" is invalid - it should be a string.
```
