### ISSUE TITLE
Volume stanza omitted

### ISSUE THREAD

**Issue by JGoor** [magicmark/composerize#524]
**Do you want to request a *feature* or report a *bug*?**
BUG

**Please provide a sample input docker run command**
```
docker run --restart=unless-stopped -d --name=readymedia1 --net=host -v /my/video/path:/media -v readymediacache:/cache -e VIDEO_DIR1=/media/my_video_files ypopovych/readymedia
```

**What is the current output?***
```
version: '3.3'
services:
    readymedia:
        restart: unless-stopped
        container_name: readymedia1
        network_mode: host
        volumes:
            - '/my/video/path:/media'
            - 'readymediacache:/cache'
        environment:
            - VIDEO_DIR1=/media/my_video_files
        image: ypopovych/readymedia
```

**What is the expected/desired output?**
```
version: '3.3'
services:
    readymedia:
        restart: unless-stopped
        container_name: readymedia1
        network_mode: host
        volumes:
            - '/my/video/path:/media'
            - 'readymediacache:/cache'
        environment:
            - VIDEO_DIR1=/media/my_video_files
        image: ypopovych/readymedia

volumes:
  readymediacache:
```
