### ISSUE TITLE
Cloudflared docker run command malformed

### ISSUE THREAD

**Issue by gabfv** [magicmark/composerize#532]
**Do you want to request a *feature* or report a *bug*?**
Bug
**Please provide a sample input docker run command**
```
docker run cloudflare/cloudflared:2022.3.4 tunnel --no-autoupdate run --token redacted
```

**What is the current output?***
```
version: '3.3'
services:
    run:
        image: run
```

**What is the expected/desired output?**
```
version: "3.3"
services:
  cloudflared:
    image: "cloudflare/cloudflared:2022.3.4"
    command: tunnel --no-autoupdate run --token redacted
```

This is the default docker run command given by Cloudflare when trying to setup a tunnel for the their Zero Trust.

**Comment by ansred** [comment]
Same issue here.

**Comment by sharevb** [comment]
Is this a valid option using args:
```
version: '3.3'
services:
    cloudflared:
        image: 'cloudflare/cloudflared:2022.3.4'
        command: tunnel
        args:
            - '--no-autoupdate'
            - run
            - '--token'
            - redacted
```

**Comment by ansred** [comment]
Here is what I use and it's working just fine via Docker Compose.

```
#############################################################################
version: '3'
services:
  cloudflare:
    container_name: cloudflared_tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token XXXXXXXXXXXXXXXXX
#############################################################################
```

or for RaspberryPi:

Use this image:
`image: cloudflare/cloudflared:latest-arm64`
