### ISSUE TITLE
Checkmk - malformed 

### ISSUE THREAD

**Issue by ansred** [magicmark/composerize#536]
**Do you want to request a *feature* or report a *bug*?**

**Please provide a sample input docker run command** https://hub.docker.com/r/checkmk/check-mk-raw/
```
docker container run -dit -p 8080:5000 --tmpfs /opt/omd/sites/cmk/tmp:uid=1000,gid=1000 -v/omd/sites --name monitoring -v/etc/localtime:/etc/localtime:ro --restart always checkmk/check-mk-raw:2.0.0-latest


```

**What is the current output?***
```
version: '3.3'
services:
    nginx:
        ports:
            - '80:80'
            - '8080:5000'
        volumes:
            - /var/run/dockerdocker
            - /omd/sites
            - '/etc/localtime:/etc/localtime:ro'
        tmpfs: '/opt/omd/sites/cmk/tmp:uid=1000,gid=1000'
        container_name: monitoring
        restart: 'always,always'
        logging:
            options:
                max-size: 1g
        image: nginx
```

**What is the expected/desired output?**
```
the restart has issue, and the image name is wrong and other attributes 
```
