### ISSUE TITLE
Handling entry commands

### ISSUE THREAD

**Issue by realSaltyFish** [magicmark/composerize#538]
**Do you want to request a *feature* or report a *bug*?**
bug
**Please provide a sample input docker run command**
```
docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:18.0.2 start-dev
```

**What is the current output?***
```
version: '3.3'
services:
    start-dev:
        ports:
            - '8080:8080'
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        image: start-dev
```

**What is the expected/desired output?**
```
version: '3.3'
services:
    keycloak:
        ports:
            - '8080:8080'
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        image: quay.io/keycloak/keycloak:18.0.2
        command: start-dev
```

**Comment by leiyang** [comment]
I had the same issue

**Comment by 1itt1eB0y** [comment]
same issue

**Comment by FX-Max** [comment]
Maybe add `--name` will be ok.

```
docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:18.0.2 --name start-dev
```

out:
```
version: '3.3'
services:
    keycloak:
        ports:
            - '8080:8080'
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        container_name: start-dev
        image: 'quay.io/keycloak/keycloak:18.0.2'
```
