### ISSUE TITLE
-d parameter breaks image

### ISSUE THREAD

**Issue by pagdot** [magicmark/composerize#542]
**Do you want to request a *feature* or report a *bug*?**

- [ ] feature request
- [X] bug report

**Please provide a sample input docker run command**
```
docker run -d ubuntu
```

**What is the current output?***
```
version: '3.3'
services:
    run:
        image: run
```

**What is the expected/desired output?**
```
version: '3.3'
services:
    run:
        image: ubuntu
```

**Are you willing/able to attempt a fix?**

Most issues can be trivially addressed by updating this mapping: 

https://github.com/magicmark/composerize/blob/dcae8ace865e2eef69e5bd27c4a9a320f56cac75/packages/composerize/src/mappings.js#L62-L66

- [ ] Is this the case for your issue?
- [ ] Would you be able to try? :) 

Thanks for following this template and making composerize better for everyone else too!
