### ISSUE TITLE
Wrong converison

### ISSUE THREAD

**Issue by edgeless634** [magicmark/composerize#544]
- [ ] feature request
- [x] bug report

**Please provide a sample input docker run command**
```
docker run -p 8000:8000 -it ctfd/ctfd
```

**What is the current output?***
```
version: '3.3'
services:
    run:
        ports:
            - '8000:8000'
        image: run
```

**What is the expected/desired output?**
```
version: '3.3'
services:
    run:
        ports:
            - '8000:8000'
        image: ctfd/ctfd
```

**Are you willing/able to attempt a fix?**

nope

Most issues can be trivially addressed by updating this mapping: 

https://github.com/magicmark/composerize/blob/dcae8ace865e2eef69e5bd27c4a9a320f56cac75/packages/composerize/src/mappings.js#L62-L66

- [ ] Is this the case for your issue?
- [ ] Would you be able to try? :) 

Thanks for following this template and making composerize better for everyone else too!
