### ISSUE TITLE
Items not converted: --cpus --cpu-shares --ip 

### ISSUE THREAD

**Issue by frankhommers** [magicmark/composerize#545]
This docker run:

```
docker run -d --restart always -p 5432:5432 --net postgres_net --ip 172.18.0.100 --name postgres2 --cpus=3 --cpu-shares=512 --log-driver json-file --log-opt max-size=100m --log-opt max-file=10 -v /srv/postgres:/var/lib/postgresql/data postgis/postgis
```

converts to this:

```
version: '3.3'
services:
    postgis:
        restart: always
        ports:
            - '5432:5432'
        network_mode: postgres_net
        container_name: postgres2
        logging:
            driver:
                - json-file
            options: 'max-size=100m,max-file=10'
        volumes:
            - '/srv/postgres:/var/lib/postgresql/data'
        image: postgis/postgis
```

But is missing cpus, cpu-shares and ip.
