### ISSUE TITLE
Wrong conversion when for Tailscale

### ISSUE THREAD

**Issue by budius** [magicmark/composerize#549]
**Do you want to request a *feature* or report a *bug*?**

- [ ] feature request
- [X ] bug report

**Please provide a sample input docker run command**

I when running the tailscale official image from https://hub.docker.com/r/tailscale/tailscale
```
docker run -d --name=tailscaled -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --network=host --privileged tailscale/tailscale tailscaled
```

**What is the current output?***
```
version: '3.3'
services:
    tailscaled:
        container_name: tailscaled
        volumes:
            - '/var/lib:/var/lib'
            - '/dev/net/tun:/dev/net/tun'
        network_mode: host
        privileged: false
        image: tailscaled
```

**What is the expected/desired output?**
```
privileged: true
image: tailscale/tailscale
```

**Are you willing/able to attempt a fix?**

Most issues can be trivially addressed by updating this mapping: 
- Would you be able to try? :) 

Sorry, I know nothing of JS and also pretty new to Docker
