### ISSUE TITLE
Support "--gpus all"

### ISSUE THREAD

**Issue by didyouexpectthat** [magicmark/composerize#550]
**Do you want to request a *feature* or report a *bug*?**

- [x] feature request
- [ ] bug report

**Please provide a sample input docker run command**
```
docker run -it --rm --gpus all -p 3000:3000 -v /opt/ai-art:/data overshard/ai-art
```

**What is the current output?***
```
version: '3.3'
services:
    ai-art:
        ports:
            - '3000:3000'
        volumes:
            - '/opt/ai-art:/data'
        image: overshard/ai-art
```

**What is the expected/desired output?**
It should pull in GPUs somehow. I don't know exactly how. I found this but it doesn't work for me at the moment but maybe someone more docker-aware could adjust.
```
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

**Are you willing/able to attempt a fix?**

Most issues can be trivially addressed by updating this mapping: 

https://github.com/magicmark/composerize/blob/dcae8ace865e2eef69e5bd27c4a9a320f56cac75/packages/composerize/src/mappings.js#L62-L66

- [No] Is this the case for your issue?
- [Not immediately] Would you be able to try? :) 

Thanks for following this template and making composerize better for everyone else too!
