### ISSUE TITLE
Wrong conversion when for cloudflare tunnel

### ISSUE THREAD

**Issue by IcyFeather233** [magicmark/composerize#554]
When creating cloudflare tunnel with docker, it's official origin command is:
`docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token xxx`

when I enter it to https://www.composerize.com/, it shows:

```
version: '3.3'
services:
    run:
        image: run
```
