### ISSUE TITLE
Publish mappings are not read properly if no space between the publish flag and the ports

### ISSUE THREAD

**Issue by ferrybig** [magicmark/composerize#558]
**Do you want to request a *feature* or report a *bug*?**

- [ ] feature request
- [x] bug report

**Please provide a sample input docker run command**
```
docker run --rm -p 4000:80 --name my-running-app my-php-app
```

**What is the current output?***
```
version: '3.3'
services:
    my-php-app:
        ports:
            - 'true'
        container_name: my-running-app
        image: my-php-app
```

**What is the expected/desired output?**
```
version: '3.3'
services:
    my-php-app:
        ports:
            - '4000:80'
        container_name: my-running-app
        image: my-php-app
```

**Are you willing/able to attempt a fix?**

Most issues can be trivially addressed by updating this mapping: 

https://github.com/magicmark/composerize/blob/dcae8ace865e2eef69e5bd27c4a9a320f56cac75/packages/composerize/src/mappings.js#L62-L66

- [ ] Is this the case for your issue?
- [x] Would you be able to try? :)  (Looking though the list, the -p flag (publish) is already listed, so the parsing goes wrong somewhere inside the generic array parsing, not sure how to modify it without causing cascading bugs)

Thanks for following this template and making composerize better for everyone else too!
