### ISSUE TITLE
Add support for health check flags

### ISSUE THREAD

**Issue by barndawgie** [magicmark/composerize#562]
**Do you want to request a *feature* or report a *bug*?**

- [X] feature request
- [ ] bug report

**Please provide a sample input docker run command**
```
docker run --name="zwave-js-ui" --restart unless-stopped -d -p 8091:8091 -p 3000:3000 --device=$ZWAVE_DEVICE:/dev/zwave --health-cmd='wget --no-verbose --spider --no-check-certificate --header "Accept: text/plain" https://localhost:8091/health || exit 1' --health-interval=60s --health-timeout=10s --health-start-period=30s --label autoheal=true -v $VOLUME_BASE/zwave-js-ui:/usr/src/app/store -v $SYNOLOGY_CERT_DIR:/certs -e TZ=$TIME_ZONE -e HTTPS=TRUE -e SSL_CERTIFICATE=/certs/ECC-cert.pem -e SSL_KEY=/certs/ECC-privkey.pem -e SESSION_SECRET=$ZWAVE_JS_UI_SESSION_SECRET zwavejs/zwave-js-ui:latest
```

**What is the current output?***
```
version: '3.3'
services:
    zwave-js-ui:
        container_name: zwave-js-ui
        restart: unless-stopped
        ports:
            - '8091:8091'
            - '3000:3000'
        devices:
            - '$ZWAVE_DEVICE:/dev/zwave'
        labels:
            - autoheal=true
        volumes:
            - '$VOLUME_BASE/zwave-js-ui:/usr/src/app/store'
            - '$SYNOLOGY_CERT_DIR:/certs'
        environment:
            - TZ=$TIME_ZONE
            - HTTPS=TRUE
            - SSL_CERTIFICATE=/certs/ECC-cert.pem
            - SSL_KEY=/certs/ECC-privkey.pem
            - SESSION_SECRET=$ZWAVE_JS_UI_SESSION_SECRET
        image: 'zwavejs/zwave-js-ui:latest'
```

**What is the expected/desired output?**
```
version: '3.3'
services:
    zwave-js-ui:
        container_name: zwave-js-ui
        restart: unless-stopped
        ports:
            - '8091:8091'
            - '3000:3000'
        devices:
            - '$ZWAVE_DEVICE:/dev/zwave'
        labels:
            - autoheal=true
        volumes:
            - '$VOLUME_BASE/zwave-js-ui:/usr/src/app/store'
            - '$SYNOLOGY_CERT_DIR:/certs'
        environment:
            - TZ=$TIME_ZONE
            - HTTPS=TRUE
            - SSL_CERTIFICATE=/certs/ECC-cert.pem
            - SSL_KEY=/certs/ECC-privkey.pem
            - SESSION_SECRET=$ZWAVE_JS_UI_SESSION_SECRET
        image: 'zwavejs/zwave-js-ui:latest'
        healthcheck:
          test: 'wget --no-verbose --spider --no-check-certificate --header "Accept: text/plain" https://localhost:8091/health || exit 1'
              interval: "60s"
              timeout: "10s"
              start_period: "30s"
```

**Are you willing/able to attempt a fix?**

Most issues can be trivially addressed by updating this mapping: 

https://github.com/magicmark/composerize/blob/dcae8ace865e2eef69e5bd27c4a9a320f56cac75/packages/composerize/src/mappings.js#L62-L66

- [X] Is this the case for your issue?
- [X] Would you be able to try? :) 

Thanks for following this template and making composerize better for everyone else too!
