### ISSUE TITLE
Multiple arguments ignoring

### ISSUE THREAD

**Issue by petrleocompel** [magicmark/composerize#9]
Ignoring multiple arguments of same type.
It's easy to reproduce.
Input
```
docker run -t --name="youtrack"  -v /data/youtrack/data/:/opt/youtrack/data/ -v /data/youtrack/backup/:/opt/youtrack/backup/ -p 80:80 -p 3232:22351 uniplug/youtrack
```
Output
```
version: 3
services:
    youtrack:
        volumes:
            - '/data/youtrack/backup/:/opt/youtrack/backup/'
        ports:
            - '3232:22351'
```
Expected output
```
version: 3
services:
    youtrack:
        volumes:
            - '/data/youtrack/data/:/opt/youtrack/data/'
            - '/data/youtrack/backup/:/opt/youtrack/backup/'
        ports:
            - '80:80'
            - '3232:22351'
```
